spring.application.name=SmartLearn

# ==================== DATASOURCE ====================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/smartlearn?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=n0m3l0

# ==================== JPA ====================
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=true

# ==================== JWT ====================
jwt.secret=miClaveSuperSecretaParaJWT2026SmartLearnQueDebeSerMuyLargaYCompleja123456789
jwt.expiration=86400000
jwt.refresh-expiration=1296000000

# ==================== MAIL / 2FA EMAIL ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cyberpathcontacto@gmail.com
spring.mail.password=utwsevhqaqsruqyl
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
smartlearn.mail.from=cyberpathcontacto@gmail.com

# ==================== LOGGING ====================
logging.level.com.cyberpath=DEBUG
logging.level.org.springframework.security=DEBUG